def banner():
   print('=================================================')
   print('               create by Ha3MrX                  ')
   print('=================================================')
   print('               ++++++++++++++++++++              ')
   print('\n                                               ')
   print('                                                 ')
   print('                                                 ')
   print('                                                 ')
   print('           HA3MrX                                ')
   print('       _,.                   ')
   print('     ,` -.)                  ')
   print('    ( _/-\\-._               ')
   print('   /,|`--._,-^|            , ')
   print('   \_| |`-._/||          , | ')
   print('     |  `-, / |         /  / ')
   print('     |     || |        /  /  ')
   print('      `r-._||/   __   /  /   ')
   print('  __,-<_     )`-/  `./  /    ')
   print('  \   `---    \   / /  /     ')
   print('     |           |./  /      ')
   print('     /           //  /       ')
   print(' \_/  \         |/  /        ')
   print('  |    |   _,^- /  /         ')
   print('  |    , ``  (\/  /_         ')
   print('   \,.->._    \X-=/^         ')
   print('   (  /   `-._//^`           ')
   print('    `Y-.____(__}             ')
   print('     |     {__)              ')
   print('           ()   V.1.0        ')
   print("\n")